"use client";
import type { ReviewEvent, ValidationRecord } from "@/lib/marketing/types";
import { date } from "./shared";
export function HistoryList({ events }: { events: ReviewEvent[] }) {
  return <div className="divide-y rounded-xl border bg-card">{!events.length && <p className="p-5 text-sm text-muted-foreground">변경 이력이 없습니다.</p>}{events.map(e => <article key={e.id} className="p-5 space-y-2"><div className="flex flex-wrap justify-between gap-2"><h3 className="text-sm font-semibold">{e.action} · {e.actor_name}</h3><time className="text-xs text-muted-foreground">{date(e.created_at)}</time></div><p className="text-sm">{e.reason}</p>{e.submitter && <p className="text-xs text-muted-foreground">제출: {e.submitter} · {e.division}</p>}<details className="text-xs text-muted-foreground"><summary className="cursor-pointer">변경 전후 · 출처 · 당시 검증 확인</summary><div className="mt-3 grid gap-3 md:grid-cols-2"><pre className="max-h-80 overflow-auto rounded bg-muted p-3 whitespace-pre-wrap break-all">변경 전{JSON.stringify(e.before_data, null, 2)}</pre><pre className="max-h-80 overflow-auto rounded bg-muted p-3 whitespace-pre-wrap break-all">변경 후{JSON.stringify(e.after_data, null, 2)}</pre></div><pre className="max-h-64 overflow-auto whitespace-pre-wrap break-all">{JSON.stringify({ source: e.source, validation: e.validation_snapshot }, null, 2)}</pre></details></article>)}</div>;
}
export function ValidationHistory({ records }: { records: ValidationRecord[] }) {
  return <details className="text-sm"><summary className="cursor-pointer">검증 이력 ({records.length}건)</summary><div className="mt-2 space-y-3">{records.map(r => <article key={r.id} className="rounded border p-3"><p>버전 {r.submission_version} · {date(r.created_at)}{r.origin === "migration_latest" && " · 기존 결과 보존 시각 (원래 생성시각 미상)"}</p><p className="text-xs text-muted-foreground">규칙 {r.result.ruleVersion} · {r.result.ai?.model ?? "규칙 검증"}</p><pre className="mt-2 max-h-48 overflow-auto text-xs whitespace-pre-wrap break-all">{JSON.stringify(r.result, null, 2)}</pre></article>)}</div></details>;
}
