"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { CATEGORIES, type Organization } from "@/lib/marketing/types";
import { api, errorMessage, selectClass } from "./shared";
export default function OrganizationEditor({ org, count = 0, onClose, onSaved }: { org?: Organization; count?: number; onClose: () => void; onSaved: () => void }) {
  const [reviewStatus,setReviewStatus] = useState(org?.review_status ?? "pending"); const [name,setName] = useState(org?.name ?? ""); const [category,setCategory] = useState(org?.category ?? "확인 필요"); const [aliases,setAliases] = useState(org?.aliases.join("\n") ?? ""); const [reason,setReason] = useState(""); const [busy,setBusy] = useState(false); const [error,setError] = useState("");
  const [requestId] = useState(() => crypto.randomUUID()); const [separate, setSeparate] = useState(false);
  async function save() { setBusy(true); try { await api("/api/marketing/organizations", { action: org ? "update" : "create", id: org?.id ?? requestId, version: org?.version, separate, name, category, aliases: aliases.split("\n").map(a => a.trim()).filter(Boolean), reason, reviewStatus }); onSaved(); } catch(e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <Dialog open onOpenChange={v => { if (!v && !busy) onClose(); }}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{org ? "회사·기관 기준 수정" : "회사·기관 등록"}</DialogTitle><DialogDescription>{org ? `소속 Contact ${count}명에 동일한 표준명과 분류가 적용됩니다.` : "표준 회사명과 분류를 먼저 등록합니다. Contact는 이후 검색·선택하여 별도로 제출합니다. 기존 회사·기관과 동일 법인인지 먼저 확인하세요."}</DialogDescription></DialogHeader><label className="text-sm space-y-1">표준명<Input value={name} onChange={e => setName(e.target.value)} /></label><label className="text-sm space-y-1">분류<select className={`${selectClass} w-full`} value={category} onChange={e => { setCategory(e.target.value); setReviewStatus("pending"); }}>{CATEGORIES.map(c => <option key={c}>{c}</option>)}</select></label><label className="text-sm space-y-1">승인 별칭 (한 줄에 하나)<textarea className="w-full border rounded-md p-2" value={aliases} onChange={e => setAliases(e.target.value)} /></label><label className="text-sm space-y-1">확인 상태<select className={`${selectClass} w-full`} value={reviewStatus} onChange={e => setReviewStatus(e.target.value as "pending" | "confirmed")}><option value="pending">확인 필요</option><option value="confirmed" disabled={category === "확인 필요"}>회사·분류 확인 완료</option></select></label><label className="text-sm space-y-1">{org ? "변경 사유 / 별도 법인 판단 근거" : "등록 사유 / 회사·기관 확인 근거"}<Input value={reason} onChange={e => setReason(e.target.value)} /></label>{!org && <label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={separate} onChange={e => setSeparate(e.target.checked)}/><span>기존 회사·기관과 이름·별칭이 비슷하지만 별도 법인임을 확인했으며, 위에 판단 근거를 기록했습니다.</span></label>}{error && <p role="alert" className="text-destructive text-sm">{error}</p>}<Button disabled={busy || !name.trim() || reason.trim().length < 2} onClick={save}>{busy ? "저장 중…" : org ? "확인 후 기준 변경" : "회사·기관 등록"}</Button></DialogContent></Dialog>;
}
