"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { FIELDS, emptyContact, type Field } from "@/lib/marketing/types";
import type { RuleCheck } from "@/lib/marketing/rules";
import { OPERATORS, RULE_FIELDS, blankRule, type Operator, type Rule, type RuleDraft, type RuleVersion, type RulesData } from "@/lib/marketing/rule-management";
import { api, date, errorMessage, selectClass } from "./shared";
import ValidationRunDialog, { type ValidationScope } from "./ValidationRunDialog";
const FIELD_OPS=["required","email","date","one_of","forbidden_values","max_length"];
export default function RuleManager({onClose}:{onClose?:()=>void}) {
 const [data,setData]=useState<RulesData|null>(null); const [editing,setEditing]=useState<Rule|null>(null); const [draft,setDraft]=useState<{id:string;revision:number}>();
 const [reason,setReason]=useState(""); const [values,setValues]=useState(""); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
 const [q,setQ]=useState(""); const [state,setState]=useState(""); const [kind,setKind]=useState(""); const [source,setSource]=useState(""); const [selected,setSelected]=useState<string[]>([]); const [history,setHistory]=useState<string|null>(null);
 const [historyPage,setHistoryPage]=useState(1);const [versions,setVersions]=useState<{rows:RuleVersion[];total:number}>({rows:[],total:0});
 const [run,setRun]=useState<ValidationScope|null>(null); const [preview,setPreview]=useState(emptyContact()); const [result,setResult]=useState<RuleCheck|null>(null);
 useEffect(()=>{const abort=new AbortController();api<RulesData>("/api/marketing/rules",undefined,abort.signal).then(setData).catch(e=>{if(!abort.signal.aborted)setError(errorMessage(e));});return()=>abort.abort();},[]);
 useEffect(()=>{if(!history)return;const abort=new AbortController();api<{rows:RuleVersion[];total:number}>(`/api/marketing/rules/${history}/versions?page=${historyPage}`,undefined,abort.signal).then(setVersions).catch(e=>{if(!abort.signal.aborted)setError(errorMessage(e));});return()=>abort.abort();},[history,historyPage]);
 async function reload(){const next=await api<RulesData>("/api/marketing/rules");setData(next);setSelected(ids=>ids.filter(id=>next.rules.some(r=>r.id===id&&r.enabled&&r.config.operator!=="builtin")));}
 function edit(rule:Rule,saved?:RuleDraft){setEditing({...rule,config:{...rule.config}});setDraft({id:saved?.id??crypto.randomUUID(),revision:saved?.revision??0});setReason(saved?.reason??"");setValues(rule.config.values?.join("\n")??"");setError("");setNotice("");}
 async function save(publish:boolean,trial=false){if(!editing||!draft)return;setBusy(true);setError("");try{
  const config={...editing.config};if(["one_of","forbidden_values"].includes(config.operator))config.values=values.split("\n").map(v=>v.trim()).filter(Boolean);
  const saved=await api<{draft:RuleDraft}>("/api/marketing/rules",{action:publish?"publish":"draft",draftId:draft.id,revision:draft.revision,ruleId:editing.id||null,baseVersion:editing.version||null,definition:{...editing,config},reason});
  setDraft({id:saved.draft.id,revision:saved.draft.revision});setResult(null);
  if(publish){setEditing(null);setNotice("새 버전을 적용했습니다. 다음 제출·재검증·승인부터 적용됩니다.");}else{setNotice("수정본을 저장했습니다. 현재 적용 규칙은 유지됩니다.");if(trial)setRun({trial:{id:saved.draft.id,revision:saved.draft.revision,title:editing.title}});}
  await reload();
 }catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function validate(){setBusy(true);setError("");try{setResult(await api<RuleCheck>("/api/marketing/rules",{action:"preview",data:preview}));}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 const rules=(data?.rules??[]).filter(r=>(`${r.title} ${r.description} ${r.code}`.includes(q))&&(!state||String(r.enabled)===state)&&(!kind||(kind==="review"?r.config.operator==="review":kind==="builtin"?r.config.operator==="builtin":!["review","builtin"].includes(r.config.operator)))&&(!source||(source==="custom"?r.code.startsWith("CUSTOM-"):!r.code.startsWith("CUSTOM-"))));
 const system=editing?.code==="EXCEL-03";
 const content=<div className="space-y-5">
  {error&&<p role="alert" className="rounded border border-destructive/30 p-3 text-sm text-destructive">{error}</p>}{notice&&<p role="status" className="rounded border border-primary/20 bg-primary/5 p-3 text-sm">{notice}</p>}
  {!data&&!error&&<p role="status">규칙을 불러오고 있습니다…</p>}
  {data&&<><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm">활성 {data.rules.filter(r=>r.enabled).length}개 / 전체 {data.rules.length}개</p>{data.editable&&<div className="flex gap-2"><Button variant="outline" disabled={!selected.length||busy} onClick={()=>setRun({initialRules:data.rules.filter(r=>selected.includes(r.id))})}>선택 규칙으로 검증 ({selected.length})</Button><Button disabled={busy} onClick={()=>edit(blankRule())}>규칙 추가</Button></div>}</div>
   {!!data.drafts?.length&&<details className="rounded-lg border p-3"><summary className="cursor-pointer text-sm font-medium">저장된 수정본 {data.drafts.length}개</summary>{data.drafts.map(d=><div key={d.id} className="flex items-center justify-between border-t py-3 mt-2 text-sm"><span>{d.definition.title} · 수정본 r{d.revision}</span><Button variant="outline" size="sm" onClick={()=>edit({...d.definition,id:d.rule_id??"",version:d.base_version??0},d)}>이어서 수정</Button></div>)}</details>}
   {editing&&<section aria-label="규칙 편집" className="rounded-xl border bg-muted/20 p-5 space-y-4"><div className="flex justify-between gap-3"><h2 className="font-semibold">{editing.id?"관리 규칙 수정":"새 규칙"}{editing.id&&<span className="ml-2 text-sm font-normal text-muted-foreground">적용본 v{editing.version}</span>}</h2><Button size="sm" variant="ghost" disabled={busy} onClick={()=>setEditing(null)}>편집 닫기</Button></div>
    {system&&<p className="rounded border bg-background p-3 text-sm">회사명 필수는 회사 연결의 시스템 제약입니다. 이름과 설명은 수정할 수 있습니다.</p>}
    <label className="block text-sm">규칙 이름<Input value={editing.title} maxLength={120} onChange={e=>setEditing({...editing,title:e.target.value})}/></label>
    <label className="block text-sm">검증 안내 / 확인 기준<textarea className="min-h-20 w-full rounded border bg-background p-2" value={editing.description} maxLength={2000} onChange={e=>setEditing({...editing,description:e.target.value})}/></label>
    <div className="grid gap-3 md:grid-cols-3"><label className="text-sm">검증 방식<select className={`${selectClass} w-full`} disabled={system} value={editing.config.operator} onChange={e=>{const op=e.target.value as Operator;setEditing({...editing,severity:op==="review"?"warning":editing.severity,config:{operator:op,...(FIELD_OPS.includes(op)?{field:editing.config.field??"phone"}:{}),...(op==="max_length"?{max:100}:{}),...(editing.config.whenField?{whenField:editing.config.whenField,whenValue:editing.config.whenValue}:{})}});}}>{Object.entries(OPERATORS).map(([op,label])=><option key={op} value={op}>{label}</option>)}</select></label>
    {FIELD_OPS.includes(editing.config.operator)&&<label className="text-sm">검사할 항목<select className={`${selectClass} w-full`} disabled={system} value={editing.config.field} onChange={e=>setEditing({...editing,config:{...editing.config,field:e.target.value as keyof typeof RULE_FIELDS}})}>{Object.entries(RULE_FIELDS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>}
    <label className="text-sm">미충족 시 처리<select className={`${selectClass} w-full`} disabled={system||editing.config.operator==="review"} value={editing.severity} onChange={e=>setEditing({...editing,severity:e.target.value as Rule["severity"]})}><option value="error">오류 · 승인 차단</option><option value="warning">확인 필요 · 근거 필수</option></select></label></div>
    {["one_of","forbidden_values"].includes(editing.config.operator)&&<label className="block text-sm">값 목록 (한 줄에 하나, 최대 100개)<textarea className="min-h-20 w-full rounded border bg-background p-2" value={values} onChange={e=>setValues(e.target.value)}/></label>}
    {editing.config.operator==="max_length"&&<label className="block text-sm">최대 글자 수<Input type="number" min={1} max={2000} value={editing.config.max??100} onChange={e=>setEditing({...editing,config:{...editing.config,max:Number(e.target.value)}})}/></label>}
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">적용 조건<select className={`${selectClass} w-full`} disabled={system} value={editing.config.whenField??""} onChange={e=>{const config={...editing.config};delete config.whenField;delete config.whenValue;if(e.target.value)config.whenField=e.target.value as keyof typeof RULE_FIELDS;setEditing({...editing,config});}}><option value="">항상 적용</option>{Object.entries(RULE_FIELDS).map(([key,label])=><option key={key} value={key}>{label} 값이 있을 때</option>)}</select></label>{editing.config.whenField&&<label className="text-sm">특정 값일 때만 적용 (비우면 모든 입력값)<Input value={editing.config.whenValue??""} onChange={e=>{const config={...editing.config};if(e.target.value)config.whenValue=e.target.value;else delete config.whenValue;setEditing({...editing,config});}}/></label>}</div>
    {editing.config.whenAnyFields&&<div className="rounded border p-3"><p className="text-xs mb-2">추가 조건: 아래 항목 중 하나라도 값이 있을 때</p><div className="flex flex-wrap gap-3">{Object.entries(RULE_FIELDS).map(([key,label])=><label key={key} className="text-xs flex gap-1"><input type="checkbox" checked={editing.config.whenAnyFields?.includes(key as keyof typeof RULE_FIELDS)} onChange={e=>{const config={...editing.config};const next=e.target.checked?[...config.whenAnyFields??[],key as keyof typeof RULE_FIELDS]:(config.whenAnyFields??[]).filter(k=>k!==key);if(next.length)config.whenAnyFields=next;else delete config.whenAnyFields;setEditing({...editing,config});}}/>{label}</label>)}</div><Button className="mt-2" size="sm" variant="ghost" onClick={()=>{const config={...editing.config};delete config.whenAnyFields;setEditing({...editing,config});}}>추가 조건 제거</Button></div>}
    <label className="flex gap-2 text-sm"><input type="checkbox" disabled={system} checked={editing.enabled} onChange={e=>setEditing({...editing,enabled:e.target.checked})}/>활성화</label>
    <label className="block text-sm">변경 사유<Input value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)}/></label>
    {editing.id&&<details className="text-sm"><summary className="cursor-pointer">현재 적용본과 변경 내용 비교</summary><div className="grid gap-3 md:grid-cols-2">{[data.rules.find(r=>r.id===editing.id),{...editing,config:{...editing.config,...(["one_of","forbidden_values"].includes(editing.config.operator)?{values:values.split("\n").filter(Boolean)}:{})}}].map((r,i)=><pre key={i} className="max-h-64 overflow-auto rounded border bg-background p-3 text-xs whitespace-pre-wrap">{i===0?"현재 적용본":"수정본"}{"\n"}{JSON.stringify({title:r?.title,description:r?.description,config:r?.config,severity:r?.severity,enabled:r?.enabled},null,2)}</pre>)}</div></details>}
    <div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy||!editing.title.trim()||reason.trim().length<2} onClick={()=>void save(false)}>초안 저장</Button><Button variant="outline" disabled={busy||editing.config.operator==="builtin"||!editing.title.trim()||reason.trim().length<2} onClick={()=>void save(false,true)}>수정본 시험 검증</Button><Button disabled={busy||!editing.title.trim()||reason.trim().length<2} onClick={()=>void save(true)}>{busy?"저장 중…":"저장 및 적용"}</Button></div>
   </section>}
   <div className="flex flex-wrap gap-2"><Input className="sm:w-72" aria-label="관리 규칙 검색" placeholder="규칙명·설명 검색" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="규칙 활성 필터" className={selectClass} value={state} onChange={e=>setState(e.target.value)}><option value="">모든 상태</option><option value="true">활성</option><option value="false">비활성</option></select><select aria-label="검증 방식 필터" className={selectClass} value={kind} onChange={e=>setKind(e.target.value)}><option value="">모든 방식</option><option value="automatic">자동 검사</option><option value="review">담당자 확인</option><option value="builtin">운영 원칙</option></select><select aria-label="규칙 출처 필터" className={selectClass} value={source} onChange={e=>setSource(e.target.value)}><option value="">모든 출처</option><option value="original">원본·기본</option><option value="custom">사용자 추가</option></select></div>
   <div className="overflow-auto rounded-xl border"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-muted"><tr><th className="p-3"><input aria-label="표시된 실행 가능 규칙 모두 선택" type="checkbox" checked={rules.some(r=>r.enabled&&r.config.operator!=="builtin")&&rules.filter(r=>r.enabled&&r.config.operator!=="builtin").every(r=>selected.includes(r.id))} onChange={e=>{const ids=rules.filter(r=>r.enabled&&r.config.operator!=="builtin").map(r=>r.id);setSelected(v=>e.target.checked?[...new Set([...v,...ids])]:v.filter(id=>!ids.includes(id)));}}/></th>{["규칙 / 출처","검사 방식·대상","적용 조건","상태·버전",""].map((label,i)=><th key={i} className="p-3 font-medium">{label}</th>)}</tr></thead><tbody>{rules.map(r=><tr key={r.id} className="border-t"><td className="p-3"><input type="checkbox" aria-label={`${r.title} 선택`} disabled={!r.enabled||r.config.operator==="builtin"} checked={selected.includes(r.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,r.id]:v.filter(id=>id!==r.id))}/></td><td className="p-3 max-w-sm"><p className="font-medium">{r.title}</p><p className="mt-1 text-xs text-muted-foreground">{r.source}</p><p className="mt-1 text-xs text-muted-foreground">{r.description}</p></td><td className="p-3">{OPERATORS[r.config.operator]}{r.config.field&&<p className="text-xs mt-1">{RULE_FIELDS[r.config.field]}</p>}</td><td className="p-3 text-xs">{r.config.whenField?`${RULE_FIELDS[r.config.whenField]} ${r.config.whenValue??"입력"} 시`:"항상"}{r.config.whenAnyFields&&<p>지정 항목 중 값이 있을 때</p>}{r.config.values&&<p>{r.config.values.join(", ")}</p>}{r.config.max&&<p>최대 {r.config.max}자</p>}</td><td className="p-3 whitespace-nowrap">{r.enabled?"활성":"비활성"} · v{r.version}<p className="text-xs text-muted-foreground mt-1">{data.versions?.find(v=>v.rule_id===r.id&&v.version===r.version)?.actor_name}<br/>{r.updated_at&&date(r.updated_at)}</p><p className="text-xs mt-1">{r.config.operator==="builtin"?"실행 제외":r.severity==="error"?"오류":"확인 필요"}</p></td><td className="p-3"><div className="flex gap-1">{data.editable&&<Button size="sm" variant="outline" onClick={()=>edit(r)}>수정</Button>}<Button size="sm" variant="ghost" onClick={()=>{setHistory(history===r.id?null:r.id);setHistoryPage(1);setVersions({rows:[],total:0});}}>이력</Button></div></td></tr>)}</tbody></table>{!rules.length&&<p className="p-8 text-center text-sm text-muted-foreground">조건에 맞는 규칙이 없습니다.</p>}</div>
   {history&&<section className="rounded-xl border p-4 space-y-3"><h2 className="font-semibold">{data.rules.find(r=>r.id===history)?.title} · 버전 이력</h2>{versions.rows.map(v=><article key={v.version} className="border-t py-3 text-sm"><div className="flex justify-between gap-3"><p>v{v.version} · {v.actor_name} · {date(v.created_at)}<span className="mt-1 block text-muted-foreground">{v.reason}</span></p>{data.editable&&<Button size="sm" variant="outline" onClick={()=>{const current=data.rules.find(r=>r.id===history)!;edit({...v.definition,id:current.id,code:current.code,version:current.version});setReason(`v${v.version} 기준 복원`);}}>이 버전으로 복원 초안</Button>}</div><details><summary className="cursor-pointer mt-2 text-xs">버전 내용</summary><pre className="max-h-60 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(v.definition,null,2)}</pre></details></article>)}<div className="flex items-center justify-end gap-2"><span className="text-xs">전체 {versions.total}개 · {historyPage} / {Math.max(1,Math.ceil(versions.total/25))}</span><Button variant="outline" size="sm" disabled={historyPage<=1} onClick={()=>setHistoryPage(p=>p-1)}>이전 버전 페이지</Button><Button variant="outline" size="sm" disabled={historyPage*25>=versions.total} onClick={()=>setHistoryPage(p=>p+1)}>다음 버전 페이지</Button></div></section>}
   <details className="rounded-xl border p-4"><summary className="cursor-pointer text-sm font-semibold">저장된 규칙 시험 검증</summary><p className="my-3 text-xs text-muted-foreground">입력값으로 현재 활성 규칙을 시험합니다. 전체 Master 비교는 ‘선택 규칙으로 검증’을 사용하세요.</p><div className="grid gap-2 sm:grid-cols-3">{(Object.entries(FIELDS) as [Field,string][]).map(([key,label])=><label key={key} className="text-xs">시험 {label}<Input maxLength={2000} value={preview[key]} onChange={e=>{setPreview({...preview,[key]:e.target.value});setResult(null);}}/></label>)}</div><Button className="mt-3" variant="outline" disabled={busy} onClick={()=>void validate()}>시험 검증</Button>{result&&<div role="status" className="mt-3 text-sm space-y-2"><p>오류 {result.violations.filter(v=>v.severity==="error").length}개 · 확인 항목 {result.violations.filter(v=>v.severity==="warning").length}개</p>{result.violations.map(v=><p key={v.id}>· {v.message}</p>)}</div>}</details>
   <details className="rounded-xl border p-4 text-sm"><summary className="cursor-pointer font-medium">시스템 보호 기준</summary><p className="mt-3 text-muted-foreground">접근 권한, 담당자 승인, 고유 DB ID·이메일 중복 제한, 회사 연결, 원본 및 감사 이력은 유지합니다. 업무 규칙의 수정·비활성화로 이 보호 장치를 해제하지 않습니다.</p></details>
  </>}{run&&<ValidationRunDialog {...run} onClose={()=>setRun(null)}/>}</div>;
 if(onClose)return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="sm:max-w-6xl max-h-[90vh] overflow-auto"><DialogHeader><DialogTitle>관리 규칙</DialogTitle><DialogDescription>업무 기준을 수정하고 선택한 규칙으로 Master를 검증합니다.</DialogDescription></DialogHeader>{content}</DialogContent></Dialog>;
 return <main className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">관리 규칙</h1><p className="mt-1 text-sm text-muted-foreground">원본과 추가 업무 기준을 버전별로 관리하고 Master를 검증합니다.</p></div><div className="flex gap-2"><Button asChild variant="outline"><Link href="/marketing/validations">검증 이력</Link></Button><Button asChild variant="outline"><Link href="/marketing">Master DB로</Link></Button></div></div>{content}</main>;
}
