"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { FIELDS, visibleData, type Contact } from "@/lib/marketing/types";
import { OUTCOMES, RUN_STATUSES, RULE_FIELDS, runInProgress, type ValidationRun, type ValidationTarget, type ValidationReport, type Outcome } from "@/lib/marketing/rule-management";
import { api, date, errorMessage, selectClass } from "./shared";
import ContactForm from "./ContactForm";
import ValidationRunDialog from "./ValidationRunDialog";
const scopeLabel={all:"전체 Master",filtered:"필터 결과 전체",selected:"직접 선택 Contact"};
function Badge({value}:{value:Outcome|null}){const k=value??"pending";return <span className={`rounded-md px-2 py-1 text-xs whitespace-nowrap ${k==="fail"||k==="error"?"bg-red-50 text-red-700":k==="review"?"bg-amber-50 text-amber-800":k==="pass"?"bg-emerald-50 text-emerald-700":"bg-muted text-muted-foreground"}`}>{OUTCOMES[k]}</span>;}
export default function ValidationResults({runId}:{runId?:string}){
 const [listing,setListing]=useState<{rows:ValidationRun[];total:number}>({rows:[],total:0});const [report,setReport]=useState<ValidationReport>();const [page,setPage]=useState(1);const [rule,setRule]=useState("");const [outcome,setOutcome]=useState("");const [q,setQ]=useState("");const [followup,setFollowup]=useState("");const [view,setView]=useState("contacts");const [severity,setSeverity]=useState("");
 const [error,setError]=useState("");const [notice,setNotice]=useState("");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);const [detail,setDetail]=useState<ValidationTarget>();const [reason,setReason]=useState("");const [nextStatus,setNextStatus]=useState("confirmed");const [followupKey,setFollowupKey]=useState(()=>crypto.randomUUID());const [form,setForm]=useState<{contact:Contact;target:ValidationTarget}>();const [rerun,setRerun]=useState(false);const [newRun,setNewRun]=useState(false);
 const params=new URLSearchParams({page:String(page),rule,outcome,q,followup,severity});const query=params.toString();
 useEffect(()=>{const abort=new AbortController();let timer:ReturnType<typeof setTimeout>;async function load(){try{const url=runId?`/api/marketing/validation-runs/${runId}?${query}`:`/api/marketing/validation-runs?page=${page}`;if(runId){const r=await api<ValidationReport>(url,undefined,abort.signal);if(abort.signal.aborted)return;setReport(r);setDetail(old=>old?r.rows.find(x=>x.contact_id===old.contact_id)??old:undefined);if(r.run&&runInProgress(r.run.status))timer=setTimeout(load,3000);}else{const r=await api<{rows:ValidationRun[];total:number}>(url,undefined,abort.signal);if(abort.signal.aborted)return;setListing(r);if(r.rows.some(x=>runInProgress(x.status)))timer=setTimeout(load,5000);}setError("");}catch(e){if(!abort.signal.aborted)setError(errorMessage(e));}finally{if(!abort.signal.aborted)setLoading(false);}}setLoading(true);void load();return()=>{abort.abort();clearTimeout(timer);};},[runId,query,page,revision]);
 function filter(update:()=>void){update();setPage(1);setDetail(undefined);}
 async function action(action:string){setBusy(true);try{await api(`/api/marketing/validation-runs/${runId}`,{action});setRevision(v=>v+1);setNotice(action==="cancel"?"검증을 취소했습니다. 이미 처리한 결과는 보존됩니다.":"같은 실행 기준으로 미처리·실행 오류를 재시도합니다.");}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function record(){if(!detail)return;setBusy(true);try{await api(`/api/marketing/validation-runs/${runId}/followups`,{requestKey:followupKey,contactId:detail.contact_id,status:nextStatus,reason,version:detail.current_version,organizationVersion:detail.current_organization_version});setDetail(undefined);setReason("");setFollowupKey(crypto.randomUUID());setRevision(v=>v+1);setNotice("확인 근거를 기록했습니다. 원래 검사 결과는 보존됩니다.");}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function change(target:ValidationTarget){setBusy(true);try{const {contact}=await api<{contact:Contact}>(`/api/marketing?view=contact&id=${target.contact_id}`);setForm({contact,target});}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function download(){setBusy(true);try{const response=await fetch(`/api/marketing/validation-runs/${runId}/export?${new URLSearchParams({rule,outcome,q,followup,severity})}`);if(!response.ok){const body=await response.json();throw new Error(body.error??"다운로드 실패");}const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="Master-DB-validation.xlsx";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice("현재 결과 필터 전체의 Excel 다운로드를 시작했습니다.");}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 const run=report?.run;const total=runId?report?.total??0:listing.total;const pages=Math.max(1,Math.ceil(total/25));
 return <main className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-semibold">{runId?"Master DB 검증 결과":"Master DB 검증 이력"}</h1><p className="mt-1 text-sm text-muted-foreground">선택한 규칙의 검사 결과와 후속 확인을 추적합니다.</p></div><div className="flex gap-2">{runId&&<Button asChild variant="outline"><Link href="/marketing/validations">검증 이력</Link></Button>}<Button asChild variant="outline"><Link href="/marketing/rules">관리 규칙</Link></Button><Button asChild variant="outline"><Link href="/marketing">Master DB로</Link></Button></div></div>
  {error&&<p role="alert" className="border border-destructive/30 rounded p-3 text-sm text-destructive">{error}<Button variant="ghost" size="sm" onClick={()=>setRevision(v=>v+1)}>새로고침</Button></p>}{notice&&<p role="status" className="rounded border bg-primary/5 p-3 text-sm">{notice}</p>}
  {!runId&&<><div className="flex justify-between"><p className="text-sm">실행 {listing.total}건</p><Button onClick={()=>setNewRun(true)}>새 검증</Button></div><div className="overflow-auto rounded-xl border"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-muted"><tr>{["실행 시각 / 담당자","대상","규칙","진행","상태",""].map((t,i)=><th key={i} className="p-3 font-medium">{t}</th>)}</tr></thead><tbody>{listing.rows.map(j=><tr key={j.id} className="border-t"><td className="p-3">{date(j.created_at)}<p className="text-xs text-muted-foreground mt-1">{j.actor_name}</p></td><td className="p-3">{scopeLabel[j.scope]} · {j.total.toLocaleString()}건</td><td className="p-3">{j.rules.length}개{j.trial&&" · 수정본 시험"}</td><td className="p-3">{j.processed.toLocaleString()} / {j.total.toLocaleString()}</td><td className="p-3">{RUN_STATUSES[j.status]}</td><td className="p-3"><Button variant="outline" size="sm" asChild><Link href={`/marketing/validations/${j.id}`}>결과 보기</Link></Button></td></tr>)}</tbody></table>{!listing.rows.length&&!loading&&<p className="p-12 text-center text-muted-foreground">아직 실행한 검증이 없습니다.</p>}</div></>}
  {run&&report&&<><section className="rounded-xl border bg-card p-5 space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{RUN_STATUSES[run.status]}{run.trial&&" · 수정본 시험"}</h2><p className="text-sm text-muted-foreground mt-1">{scopeLabel[run.scope]} {run.total.toLocaleString()}건 · 선택 규칙 {run.rules.length}개 · {run.actor_name}</p></div><div className="flex flex-wrap gap-2">{runInProgress(run.status)?<Button variant="outline" disabled={busy} onClick={()=>void action("cancel")}>검증 취소</Button>:["failed","cancelled","completed_with_errors"].includes(run.status)&&<Button variant="outline" disabled={busy} onClick={()=>void action("retry")}>미처리·오류 재시도</Button>}{!run.trial&&<Button variant="outline" disabled={busy} onClick={()=>setRerun(true)}>최신 기준으로 다시 검증</Button>}<Button variant="outline" disabled={busy||!report.total} onClick={()=>void download()}>결과 Excel 다운로드</Button></div></div><div role="progressbar" aria-label="검증 진행률" aria-valuemin={0} aria-valuemax={run.total} aria-valuenow={run.processed} className="h-2 rounded bg-muted overflow-hidden"><div className="h-full bg-primary transition-all" style={{width:`${run.total?run.processed/run.total*100:0}%`}}/></div><p className="text-xs text-muted-foreground">처리 {run.processed.toLocaleString()} / {run.total.toLocaleString()}건 · 기준 시각 {date(run.created_at)}{runInProgress(run.status)&&" · 화면을 닫아도 검증이 이어집니다."}</p>{run.last_error&&<p className="text-sm text-destructive">{run.last_error}</p>}<details className="text-sm"><summary className="cursor-pointer">실행 범위와 규칙 버전</summary><p className="text-xs mt-2">{Object.entries(run.filters).filter(([,v])=>v!==""&&v!==false).map(([k,v])=>`${({q:"검색",category:"분류",department:"관리부서",issues:"정비 필요",sort:"정렬",direction:"방향"} as Record<string,string>)[k]??k}: ${String(v)}`).join(" · ")||"전체"}</p><ul className="mt-2 space-y-1">{run.rules.map((r,i)=><li key={i}>{r.title} · {run.trial?"초안 r":"v"}{r.version}</li>)}</ul></details></section>
   {report.comparisonChanged&&<p className="rounded border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">실행 이후 비교 대상 Master 또는 회사 기준이 변경되었습니다. 중복·회사 판정은 당시 자료 기준이며, 확인 완료 전에 최신 기준 재검증이 필요합니다.</p>}
   {report.rulesChanged&&<p className="rounded border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">실행 이후 적용 규칙이 변경되었습니다. 아래 결과는 당시 버전 기준입니다. 최신 기준 재검증이 필요합니다.</p>}
   <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{Object.entries(OUTCOMES).map(([k,label])=><button key={k} className="rounded-xl border bg-card p-4 text-left hover:bg-muted/30" disabled={k==="pending"} onClick={()=>filter(()=>setOutcome(k))}><span className="text-xs text-muted-foreground">{label} Contact</span><strong className="block mt-1 text-xl">{(report.counts[k as Outcome]??0).toLocaleString()}</strong></button>)}</div>
   <div className="flex gap-2"><Button variant={view==="contacts"?"default":"outline"} onClick={()=>setView("contacts")}>Contact별 결과</Button><Button variant={view==="rules"?"default":"outline"} onClick={()=>setView("rules")}>규칙별 집계</Button></div>
   {view==="rules"?<div className="rounded-xl border overflow-auto"><table className="w-full min-w-[650px] text-sm text-left"><thead className="bg-muted"><tr><th className="p-3">규칙</th><th className="p-3">판정</th><th className="p-3">Contact</th><th className="p-3">소속 회사·기관</th></tr></thead><tbody>{report.ruleCounts.map(c=><tr key={`${c.rule_index}-${c.outcome}-${c.severity}`} className="border-t"><td className="p-3"><button className="text-primary hover:underline" onClick={()=>{filter(()=>{setRule(String(c.rule_index));setOutcome(c.outcome);});setView("contacts");}}>{run.rules[c.rule_index-1]?.title}</button></td><td className="p-3"><Badge value={c.outcome}/></td><td className="p-3">{c.count.toLocaleString()}건</td><td className="p-3">{c.companies.toLocaleString()}곳</td></tr>)}</tbody></table><p className="p-3 text-xs text-muted-foreground">규칙마다 집계하므로 한 Contact가 여러 행에 포함됩니다. 회사 수는 각 판정에 영향받는 고유 회사 수입니다.</p></div>:<><div className="flex flex-wrap gap-2"><Input aria-label="검증 결과 검색" className="sm:w-64" placeholder="회사명·성명·DB ID 검색" value={q} onChange={e=>filter(()=>setQ(e.target.value))}/><select aria-label="결과 규칙 필터" className={selectClass} value={rule} onChange={e=>filter(()=>setRule(e.target.value))}><option value="">모든 선택 규칙</option>{run.rules.map((r,i)=><option key={i} value={i+1}>{r.title} v{r.version}</option>)}</select><select aria-label="판정 필터" className={selectClass} value={outcome} onChange={e=>filter(()=>setOutcome(e.target.value))}><option value="">모든 판정</option>{Object.entries(OUTCOMES).filter(([k])=>k!=="pending").map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="규칙 등급 필터" className={selectClass} value={severity} onChange={e=>filter(()=>setSeverity(e.target.value))}><option value="">모든 규칙 등급</option><option value="error">오류</option><option value="warning">확인 필요</option></select><select aria-label="후속 처리 필터" className={selectClass} value={followup} onChange={e=>filter(()=>setFollowup(e.target.value))}><option value="">모든 처리 상태</option><option value="open">미처리 / 재확인</option><option value="confirmed">확인 완료</option><option value="deferred">보류</option><option value="submitted">변경 요청 제출</option></select></div>
   <div className="rounded-xl border overflow-auto"><table className="w-full min-w-[900px] text-sm text-left"><thead className="bg-muted"><tr>{["DB ID","회사명 / 성명","대표 결과","확인 항목","후속 처리",""].map((label,i)=><th key={i} className="p-3 font-medium">{label}</th>)}</tr></thead><tbody>{report.rows.map(t=><tr key={t.contact_id} className="border-t"><td className="p-3"><button className="text-primary hover:underline" onClick={()=>{setDetail(t);setReason("");setFollowupKey(crypto.randomUUID());}}>{t.snapshot.db_id}</button></td><td className="p-3">{visibleData(t.snapshot).company||"회사명 미입력"}<p className="mt-1 text-muted-foreground">{t.snapshot.data.name||"성명 미입력"}</p></td><td className="p-3"><Badge value={t.outcome}/>{t.stale&&<p className="mt-2 text-xs text-amber-700">현재 데이터 변경됨</p>}</td><td className="p-3 max-w-sm">{t.issue_count}개<p className="mt-1 text-xs text-muted-foreground">{t.results.find(r=>["error","fail","review"].includes(r.outcome))?.detail.message}</p></td><td className="p-3 text-xs">{t.followup_stale?"기준 변경 · 재확인":t.followup_status==="confirmed"?"확인 완료":t.followup_status==="deferred"?"보류":t.followup_status==="submitted"?`변경 요청 · ${t.submission_status??"제출"}`:"미처리"}</td><td className="p-3"><Button size="sm" variant="outline" disabled={busy||!t.current_version||!!t.submission_id} onClick={()=>void change(t)}>변경 요청 작성</Button></td></tr>)}</tbody></table>{!report.rows.length&&!loading&&<p className="p-12 text-center text-muted-foreground">조건에 맞는 결과가 없습니다.</p>}</div></>}
  </>}
  {loading&&<p role="status" className="text-sm text-muted-foreground">불러오는 중…</p>}{view==="contacts"&&<div className="flex items-center justify-between text-sm text-muted-foreground"><span>{total.toLocaleString()}건 · 페이지당 25건</span><div className="flex items-center gap-3"><Button variant="outline" size="sm" disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)}>이전</Button>{page} / {pages}<Button variant="outline" size="sm" disabled={page>=pages||loading} onClick={()=>setPage(p=>p+1)}>다음</Button></div></div>}
  {detail&&run&&<Dialog open onOpenChange={open=>{if(!open&&!busy)setDetail(undefined);}}><DialogContent className="sm:max-w-4xl max-h-[90vh] overflow-auto"><DialogHeader><DialogTitle>{detail.snapshot.db_id} · {detail.snapshot.data.name||"성명 미입력"}</DialogTitle><DialogDescription>검사 당시 값·규칙과 담당자 확인 기록입니다.</DialogDescription></DialogHeader>{error&&<p role="alert" className="text-destructive text-sm">{error}</p>}{detail.stale&&<p className="text-sm text-amber-700">현재 Contact/회사 정보가 바뀌었습니다. 확인 완료 처리 전에 재검증하세요.</p>}<div className="space-y-3">{detail.results.map(r=><article key={r.id} className="rounded-lg border p-3 text-sm"><div className="flex justify-between gap-2"><h3 className="font-semibold">{run.rules[r.rule_index-1]?.title} · v{run.rules[r.rule_index-1]?.version}</h3><Badge value={r.outcome}/></div><p className="mt-2">{r.detail.message}</p>{r.detail.field&&<p className="mt-2 text-xs">{RULE_FIELDS[r.detail.field as keyof typeof RULE_FIELDS]}: {r.detail.actual||"(빈 값)"}</p>}{!!r.detail.related?.length&&<p className="mt-2 text-xs">관련 후보: {r.detail.related.map(x=>x.dbId??`${x.name} · ${x.category}`).join(", ")}</p>}</article>)}</div><details><summary className="cursor-pointer text-sm">검사 당시 Contact 값</summary><dl className="grid grid-cols-[140px_1fr] gap-2 mt-3 text-sm">{Object.entries(FIELDS).map(([k,label])=><div key={k} className="contents"><dt className="text-muted-foreground">{label}</dt><dd className="break-all">{visibleData(detail.snapshot)[k as keyof typeof FIELDS]||"—"}</dd></div>)}</dl></details>{detail.context.companyContacts&&<p className="text-xs text-muted-foreground">실행 당시 회사 전체 Contact {detail.context.companyContacts}명. 선택 범위 밖 Contact는 이번 결과의 직접 검사 대상에 포함되지 않습니다.</p>}
   <section className="border-t pt-4 space-y-3"><h3 className="font-semibold text-sm">담당자 확인 기록</h3><p className="text-xs text-muted-foreground">확인 기록은 원래 검사 판정을 바꾸지 않습니다. 값을 수정하려면 변경 요청을 작성하세요.</p><label className="block text-sm">처리 상태<select className={`${selectClass} w-full`} value={nextStatus} onChange={e=>setNextStatus(e.target.value)}><option value="confirmed">확인 완료</option><option value="deferred">보류</option></select></label><label className="block text-sm">확인 근거<textarea className="w-full rounded border p-2" value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)}/></label><div className="flex flex-wrap gap-2"><Button disabled={busy||reason.trim().length<2||!detail.current_version||(!detail.processed&&nextStatus==="confirmed")||((detail.stale||report?.rulesChanged||report?.comparisonChanged)&&nextStatus==="confirmed")} onClick={()=>void record()}>확인 기록 저장</Button><Button variant="outline" disabled={busy||!!detail.submission_id||!detail.current_version} onClick={()=>void change(detail)}>변경 요청 작성</Button></div>{detail.followups.map(f=><p key={f.id} className="border-t pt-2 text-xs">{date(f.created_at)} · {f.actor_name} · {f.status==="confirmed"?"확인 완료":f.status==="submitted"?"변경 제출":"보류"}<span className="block mt-1">{f.reason}</span></p>)}</section>
  </DialogContent></Dialog>}
  {form&&<ContactForm initial={visibleData(form.contact)} dbId={form.contact.db_id} initialOrganizationId={form.contact.organization_id} fixedRequestKey={form.target.submission_request_key} source={{validationRunId:runId,validationContactId:form.target.contact_id}} onClose={()=>setForm(undefined)} onSaved={()=>{setForm(undefined);setDetail(undefined);setRevision(v=>v+1);setNotice("변경 요청을 제출했습니다. 기존 검수·승인 후 Master에 반영됩니다.");}}/>}
  {newRun&&<ValidationRunDialog onClose={()=>setNewRun(false)}/>}{rerun&&run&&<ValidationRunDialog initialScope={run.scope} filters={run.filters} filteredCount={run.total} initialRules={run.rules} ids={report?.selectedIds??[]} onClose={()=>setRerun(false)}/>}
 </main>;
}
