"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { OPERATORS, type Rule, type RulesData } from "@/lib/marketing/rule-management";
import { api, errorMessage, selectClass } from "./shared";
export interface ValidationScope { filters?: Record<string,string|boolean>; filteredCount?: number; ids?: string[]; initialRules?: Rule[]; trial?: {id:string; revision:number; title:string}; initialScope?: "all"|"filtered"|"selected" }
export default function ValidationRunDialog({ onClose, filters, filteredCount, ids = [], initialRules = [], trial, initialScope }: ValidationScope & {onClose:()=>void}) {
  const router=useRouter(); const [rules,setRules]=useState<Rule[]>([]); const [chosen,setChosen]=useState(initialRules.map(r=>r.id)); const [scope,setScope]=useState(initialScope??(ids.length ? "selected" : filters ? "filtered" : "all"));
  const [total,setTotal]=useState<number>(); const [q,setQ]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [key,setKey]=useState(()=>crypto.randomUUID());
  useEffect(()=>{ const abort=new AbortController(); Promise.all([api<RulesData>("/api/marketing/rules",undefined,abort.signal),api<{total:number}>("/api/marketing?view=meta",undefined,abort.signal)]).then(([r,m])=>{ setRules(r.rules); setTotal(m.total); }).catch(e=>{if(!abort.signal.aborted)setError(errorMessage(e));}); return()=>abort.abort(); },[]);
  const available=rules.filter(r=>r.enabled&&r.config.operator!=="builtin"); const matches=available.filter(r=>`${r.title} ${r.description}`.includes(q));
  const count=scope==="all"?total:scope==="filtered"?filteredCount:ids.length; const chosenRules=available.filter(r=>chosen.includes(r.id));
  function toggle(id:string) {setChosen(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);setKey(crypto.randomUUID());}
  async function start() {setBusy(true);setError("");try{const result=await api<{id:string}>("/api/marketing/validation-runs",{requestKey:key,scope,filters:filters??{},ids:scope==="selected"?ids:[],rules:chosenRules.map(r=>({id:r.id,version:r.version})),trialId:trial?.id,trialRevision:trial?.revision});router.push(`/marketing/validations/${result.id}`);}catch(e){setError(errorMessage(e));setBusy(false);}}
  return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="sm:max-w-2xl max-h-[90vh] overflow-auto"><DialogHeader><DialogTitle>{trial?"수정본 시험 검증":"Master DB 규칙 검증"}</DialogTitle><DialogDescription>실행 당시 데이터와 규칙으로 검사합니다. Master 반영은 기존 검수·승인을 거칩니다.</DialogDescription></DialogHeader>
    <label className="space-y-2 text-sm">검증 대상<select aria-label="검증 대상" className={`${selectClass} w-full`} value={scope} disabled={busy} onChange={e=>{setScope(e.target.value as typeof scope);setKey(crypto.randomUUID());}}><option value="all">전체 Master · {total?.toLocaleString()??"조회 중"}건</option>{filters&&<option value="filtered">현재 필터 결과 전체 · {filteredCount?.toLocaleString()}건</option>}{ids.length>0&&<option value="selected">직접 선택한 Contact · {ids.length.toLocaleString()}건</option>}</select></label>
    <p className="text-xs text-muted-foreground">중복 비교는 선택 범위 밖을 포함한 전체 Master 기준입니다. 실제 실행 대상 수는 서버에서 확정합니다.</p>
    {trial?<div className="rounded-lg border bg-primary/5 p-4">수정본: {trial.title} · 초안 r{trial.revision}<p className="mt-2 text-xs">시험 결과는 현재 적용 규칙에 영향을 주지 않습니다.</p></div>:<><div className="flex items-center justify-between"><h3 className="font-medium text-sm">적용 규칙 {chosenRules.length}개</h3><Button variant="ghost" size="sm" disabled={busy} onClick={()=>{setChosen(chosenRules.length===available.length?[]:available.map(r=>r.id));setKey(crypto.randomUUID());}}>{chosenRules.length===available.length?"전체 해제":"실행 가능 규칙 전체 선택"}</Button></div><Input aria-label="검증할 규칙 검색" placeholder="규칙 검색" value={q} onChange={e=>setQ(e.target.value)}/><div className="max-h-80 overflow-y-auto divide-y rounded-lg border">{matches.map(r=><label key={r.id} className="flex cursor-pointer gap-3 p-3 hover:bg-muted/30"><input type="checkbox" checked={chosen.includes(r.id)} disabled={busy} onChange={()=>toggle(r.id)}/><span className="text-sm"><strong className="font-medium">{r.title}</strong> <span className="text-muted-foreground">v{r.version}</span><span className="mt-1 block text-xs text-muted-foreground">{OPERATORS[r.config.operator]}</span></span></label>)}</div><p className="text-xs text-muted-foreground">비활성 규칙과 실행할 수 없는 운영 원칙은 제외됩니다.</p></>}
    {error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button disabled={busy||!count||(!trial&&!chosenRules.length)} onClick={()=>void start()}>{busy?"검증 대상을 확정하고 있습니다…":`${trial?1:chosenRules.length}개 규칙으로 ${count?.toLocaleString()??"—"}건 검증`}</Button>
  </DialogContent></Dialog>;
}
